### ISSUE TITLE
Alembic Animation Motion Blur faled

### ISSUE THREAD

**Issue by johnartune** [keijiro/PostProcessingDemo#1]
Sorry for troubling you.When I test the Alembic Importer [https://github.com/unity3d-jp/AlembicImporter](url), Import a little animated mesh, but can't get any Motion Vectors color. If you give us some help. I already send you a mail in your keijiro@gmail.com. Thank you for your help.

**Comment by keijiro** [comment]
I've replied via email.

I'm closing this ticket because it's not related to this repository.
