### ISSUE TITLE
ArgumentException: Shader not found (Hidden/Post FX/Grain Generator)

### ISSUE THREAD

**Issue by jBachalo** [keijiro/PostProcessingDemo#2]
Get the following error when trying to play. Unity 5.6.0f3

ArgumentException: Shader not found (Hidden/Post FX/Grain Generator)

**Comment by keijiro** [comment]
Could you try Assets->Reimport All?

By the way, which platform are you using? Windows, macOS or Linux?

**Comment by jBachalo** [comment]
Thanks. MacOS. Was able to resolve by rebooting, reimporting. Not sure why this error cropped up in the first place.

**Comment by keijiro** [comment]
Thanks for confirming. I also experienced the same error a few times but still don't know what the root cause is.
